task: classify

Dataset: XRD.XRD
train_steps: 5e5

num_classes: 7
icsd: true
open_access: false
rruff: true
soup: true

dataset:
  num_classes: ${num_classes}
  icsd: ${icsd}
  open_access: ${open_access}
  rruff: ${rruff}
  soup: ${soup}

Aug: Identity
Eyes: Identity
Trunk: Identity
Predictor: Identity

task_name: ${dataset.num_classes}-Way
